version: 0.2
phases:
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
    - mv target/hotel-backend-0.0.1-SNAPSHOT.jar hotel-backend-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - hotel-backend-0.0.1-SNAPSHOT.jar